### ISSUE TITLE
Ajouter un schéma de principe au readme

### ISSUE THREAD

**Issue by aurelien-baudet** [zetapush/zetapush-next-open-specification#30]

**Comment by damienld22** [comment]
Qu'est type de schéma de principe est nécessaire dans le README.md ?

Faut-il un schéma d'archi haut niveau au sens infra ? Plutôt un schéma d'archi au niveau applicatif avec les différentes interactions entre les éléments ? (Front / Cloud Service / Custom cloud service...)
