### ISSUE TITLE
préciser comment on accède aux services custom au travers de ZetaPush

### ISSUE THREAD

**Issue by aurelien-baudet** [zetapush/zetapush-next-open-specification#31]
Expliquer pour que les devs puissent comprendre les interactions entre les différentes parties (front, ZetaPush, NodeJS)

**Comment by damienld22** [comment]
Voilà comment je vois les choses : 

Le développeur créé ses _Custom Cloud Services_ en créant des classes dans le dossier de son choix. Ce dossier sera soit le dossier `server` à la racine d'un projet initialisé avec la CLI, soit un autre dossier que le développeur spécifiera lors de son déploiement : `zeta push --server /path/to/server/folder`.

Une fois que le développeur a déployé ses _Custom Cloud Services_, ces derniers sont accessibles de la même manière qu'un _Cloud Service_ existant sur ZetaPush.

Il pourra par exemple écrire : 

```javascript
// MyCustomService est un Custom Cloud Service déployé par le développeur
const customService = new MyCustomService()

/**
 *  MyCustomService intègre une Cloud Function "myCloudFunction()" que le développeur a écrit
 *  "myCloudFunction()" est asynchrone
 */
const result = await customService.myCloudFunction();
```

Qu'en pensez vous ?

**Comment by aurelien-baudet** [comment]
Faire le schéma de principe (#30)
