### ISSUE TITLE
Nommer et définir les var d'env et les sandbox/apps/envs

### ISSUE THREAD

**Issue by pablo-abreu** [zetapush/zetapush-next-open-specification#42]
ex : 
ZETA_SANDBOX_DEVELOPER_LOGIN
ZETA_SANDBOX_DEVELOPER_PASSWORD
ZETA_SANDBOX_ZBO_URL
ZETA_SANDBOX_DEPLOYMENT_ID

CUSTOM_APP_xxx (TODO : trouver un préfixe (ou autre convention) pour les var developpeur)

**Comment by ghoullier** [comment]
Actuellement les variables utilisée au sein du worker sont les suivantes:

ZP_ZBO_URL
ZP_SANDBOX_ID
ZP_USERNAME
ZP_PASSWORD

Il n'y pas encore d'injection de variables définis par le développer.

**Comment by damienld22** [comment]
Voici ma proposition : 

`ZP_LOGIN` : Login du développeur de son compte ZetaPush
`ZP_PASSWORD` : Mot de passe du développeur de son compte ZetaPush
`ZP_APP` : Nom de l'application (identification unique d'une application sur un compte défini)
`ZP_URL` : URL de l'API (Utile seulement en interne ZetaPush)

**ZP_WORKER_SERVICE_ID** est-il nécessaire ?

**Comment by damienld22** [comment]
`ZP_DEVELOPER_LOGIN` : Login du compte développeur sur la plateforme ZetaPush
`ZP_DEVELOPER_PASSWORD` : Password du compte développeur sur la plateforme ZetaPush
`ZP_PLATFORM_URL` : URL de l'API
`ZP_WORKER_REGISTRATION_ID` : Identifiant du service de Queue utilisé pour le Worker
`ZP_APP_NAME` : Nom unique de l'application sur un compte ZetaPush
`ZP_ENV_NAME` : Nom de l'environnement utilisé pour une application donnée (Pas utilisable actuellement)
