### ISSUE TITLE
Utilisation du broadcast

### ISSUE THREAD

**Issue by ghoullier** [zetapush/zetapush-next-open-specification#47]
# Existant
Les macroscript ZetaPush V2 permette à un developpeur de **broadcaster** le résultats d'une macro sur une ressource donnée.
Une ressource est une chaine de caractère permettant d'identifié un utilisateur ou une groupe d'utilisateur.

```zms
macroscript hello() {
} broadcast('userKey') {
	key: 'value'
}
```

Dans le cadre de celtia, le developpeur de cloud function doit avoir la même possibilité.

# Proposition 1

Normalisation de la structure de données retournée par les méthodes

```ts
module.exports = class {
	method1(parameters, response) {
		// Retourne le résultat à l'utilisateur ayant l'userKey passé en paramètre
		return response.broadcast({
			key: 'value'
		}, 'userKey');
	}
	method2(parameters, response) {
		// Retourne le résultat à l'utilisateur appelant
		return response.notify({
			key: 'value'
		});
	}
}
```

## Avantages: 
- On conserve la notion 1 return / 1 broadcast par cloud function

## Inconvénients:
- Ça complexifie les cas simples

# Proposition 2

Le broadcast est utilisé comme une API de messaging et non un type de retour

```ts
module.exports = class {
	method1(parameters, response) {
		// Envoie un message à l'utilisateur ayant l'userKey passé en paramètre
		response.broadcast({
			key: 'value'
		}, 'userKey');
		response.broadcast({
			key2: 'value2'
		}, 'userKey2');
		// L'utilisateur ayant appelé la cloud function lui reçoit le retour de la cloud function
	}
	method2(parameters, response) {
		// Retourne le résultat à l'utilisateur appelant
		return {
			key: 'value'
		}
	}
}
```

## Avantages: 
- Le développeur peut faire autant d'appel à broadcast qu'il le souhaite dans son code

## Inconvénients:
- On change la logique avec les macroscripts v2

**Comment by damienld22** [comment]
Cette première proposition me plait bien mais je ne comprend ce qu'est réellement le paramètre `response` ? 

L'appelant de la _Cloud Function_ est obligé de le passer en paramètre ?

**Comment by ghoullier** [comment]
Non c'est injecté par le code du SDK. Ce qui est envoyé par l'application client c'est le premier paramètre **parameters**.

**Comment by damienld22** [comment]
Le mot clé **broadcast** est bien je trouve après je pensais à **transmit** ?

**Comment by ghoullier** [comment]
Oui **notify** aussi.

**Comment by damienld22** [comment]
Oui je préfère **notify** du coup

**Comment by raphael22** [comment]
Je trouve **broadcast** plus parlant.

**Comment by aurelien-baudet** [comment]
Et bah je vais encore proposer autre chose : 

**Cas simples et récurrents :**
```javascript
module.exports = class {
        // le résultat est envoyé à tous les destinataires grâce à sendTo
        @sendTo(['user1',        // envoie à un utilisateur identifié par son id applicatif
                 () => {...}],   // provider qui génère une liste ou un user à partir des paramètres et du retour de la fonction
                 includeSender=true) 
	method0(monParam1Amoi, monParam2Amoi) {
                // je fais mon pitit calcul
                result = ...
                // je retourne le résultat
		return result
	}
```
```javascript
module.exports = class {
        constructor(messagingService) {}

 	method0(monParam1Amoi, monParam2Amoi) {
                // je fais mon pitit calcul
                result = ...
                // je retourne le résultat
		this.messagingService.sendTo(result, 'user1', ...)
	}
```

**Cas avancés :**
```javascript
module.exports = class {
        constructor(messagingService) {}
       
	method1(monParam1Amoi, monParam2Amoi) {
                // je fais mon pitit calcul
                result1 = ...
                // je retourne le résultat
		this.messagingService.sendTo(result1, 'user1', ...)
                
                // je fais mon pitit calcul
                result2 = ...
                // je retourne le résultat
		this.messagingService.sendTo(result2, 'user1', ...)
	}

	method2(monParam1Amoi, monParam2Amoi) {
		// Retourne le résultat à l'utilisateur appelant
		return {
			key: 'value'
		}
	}
}
```

Le but est de se concentrer sur le code utile et d'extraire au maximum les problématiques techniques du code. Donc on laisse l'utilisateur coder une fonction avec ses propres paramètres et son propre retour et zetapush lui permet d'ajouter des comportements sans lui demander de casser son code (ou le moins possible). Ceci toujours dans l'optique de pouvoir faire du test unitaire sur le comportement de la fonction et non pas tester zetapush

**Comment by ghoullier** [comment]
Je suis pas super fan de l'annotation pour le broadcast, car ça oblige a mettre la userKey en dur en dehors de la cloud function. Je suis plutot partisant d'une API, ça permet de fonctionner simplement en JS et TS.
L'utilisation du service de messaging est une bonne approche pour l'implémenter rapidement par contre!!

**Comment by ghoullier** [comment]
@damienld22 Voila comment on peut l'implémenter avec l'API actuelle.

```typescript
const { Messaging } = require('@zetapush/platform');

module.exports = class Api {
  static get injected() {
    return [Messaging];
  }
  constructor(messaging) {
    this.messaging = messaging;
  }
  addMessageToConversation(parameters) {
    this.messaging.send({
      channel: '',
      target: '',
      data: parameters.message
    });
    return parameters.message;
  }
}
```
