### ISSUE TITLE
Fonctionnel commande : zeta push

### ISSUE THREAD

**Issue by damienld22** [zetapush/zetapush-next-open-specification#52]
# Objectif

Le but de cette issue est de spécifier le fonctionnement de la commande `zeta push`. Le point de vue fonctionnel pour le développeur sera mis en avant mais différents éléments techniques seront présentés par moment pour s'assurer de la bonne compréhension de chacun.

## But de la commande

> Déploiement du code du développeur. À la fois le code front et le code back

## Paramètres de la commande

La commande standard est : `zeta push`

* `login` : Identifiant de compte du développeur
* `password` : Mot de passe du compte développeur (optionnel, peut être demandé en prompt)
* `name` : Nom de l'application cible
* `url` : Url l'environnement de développement (Utile seulement en interne ZetaPush)
* `back` : Path de mon code serveur
* `front` : Path de mon code client
* `front-only` : Déploiement du code front seulement
* `back-only` : Déploiement du code back seulement

## Process de lecture de la configuration

Liste et nommage des données à rechercher : 

> Variables d'environnement à spécifier : #42 

```console
ZP_FRONT : Chemin du code front
ZP_BACK : Chemin du code back
ZP_LOGIN : Login du développeur de son compte ZetaPush
ZP_PASSWORD : Mot de passe du développeur de son compte ZetaPush
ZP_NAME : Nom de l'application (identification unique d'une application sur un compte défini)
ZP_URL : URL de l'API (Utile seulement en interne ZetaPush)
```

Lors d'un déploiement, la CLI cherche la configuration a utiliser (Configuration de compte ou configuration de l'application). Voici le processus (Chaque configuration trouvée écrase la donnée précédente) : 

1. Recherche dans les variables d'environnement 
2. Recherche dans le fichier `.zetarc` du _HOME_ du développeur
3. Recherche dans le fichier `.zetarc` du dossier courant de l'application
4. Recherche dans le `package.json` en utilisant la syntaxe suivante : 

```json
{
    "zetapush": {
        "name" : "myApp",
        "url" : "http://hq.zpush.io:9080/zbo/pub/business/",
        "front" : "./front",
        "server" : "./server",
        "login" : "user@gmail.com",
        "password" : "password"
    },
}
```

## Details

- Lancement de la commande `zeta init` si nécessaire

- Si rien n'est spécifié paramètre de la ligne de commande, un déploiement du code front et du code back est fait en suivant le process de lecture de la configuration.

- Si le paramètre `--front-only` seulement le code front est déployé en suivant le process de lecture de la configuration.

- Si le paramètre `--back-only` seulement le code back est déployé en suivant le process de lecture de la configuration.

- Un retour dans la console est fait pour suivre la progression

- Si un déploiement du front est effectif, un retour dans la console est fait pour retourner l'URL du front déployé.

## Sortie de la console

Dans un cas complet, voici la sortie de la console suite à un déploiement avec `zeta push`.

```console
Deploying your application on production environment:
      ✓ Code uploaded
      | Publishing custom services on node 1   ██████░░░░░░
      - Publishing custom services on node 2   ████████░░░░
      / Publishing custom services on node 3   ██░░░░░░░░░░
```

Et lorsque tout est prêt : 

```console
Deploying your application on production environment:
      ✓ Code uploaded
      ✓ Custom services published on node 1
      ✓ Custom services published on node 2
      ✓ Custom services published on node 3

Your custom services are ready and accessible through ZetaPush and your application is available on : https://zetapush.apps.com/myApp/oidjhoh
```

**Comment by aurelien-baudet** [comment]
Je reprends ce qui avait été mis dans la #41 :

---

Voici une première proposition du fonctionnement de `zeta push` : 

# Pré-requis 

- Se trouver dans un projet initialisé avec `zeta init`. Typiquement, il faut être dans le dossier où se trouve un `.package.json` avec les dépendances à ZetaPush et un fichier `.zetapush` à la racine de son `$HOME`.

# Push sans distinction
`zeta push`

- Déploiement du code back se trouvant dans le dossier spécifié dans le path dans du `.package.json`
- Déploiement du code front se trouvant dans le dossier spécifié dans le path dans du `.package.json`
- Création d'un zip, puis envoi à la plateforme ZetaPush
- Suivi de progression du déploiement dans la console
- Les _custom cloud services_ déployés sont à présent accessible via l'autocompletion de l'IDE

# Push en déployant seulement le front
`zeta push --front-only`

- Déploiement du code front se trouvant dans le dossier spécifié dans le path dans du `.package.json`
- Création d'un zip, puis envoi à la plateforme ZetaPush
- Suivi de progression du déploiement dans la console

# Push en déployant seulement le code server
`zeta push --server-only`

- Déploiement du code server se trouvant dans le dossier spécifié dans le path dans du `.package.json`
- Création d'un zip, puis envoi à la plateforme ZetaPush
- Suivi de progression du déploiement dans la console
- Les _custom cloud services_ déployés sont à présent accessible via l'autocompletion de l'IDE

# Push en spécifiant les chemins de chaque partie
`zeta push --front /path/to/front --back /path/to/back`

- Déploiement du code back se trouvant dans le path spécifié dans la CLI
- Déploiement du code front se trouvant dans le path spécifié dans la CLI
- Création d'un zip, puis envoi à la plateforme ZetaPush
- Suivi de progression du déploiement dans la console
- Les _custom cloud services_ déployés sont à présent accessible via l'autocompletion de l'IDE

# Push en déployant seulement le front avec un path spécifié
`zeta push --front-only /path/to/front`

- Déploiement du code front se trouvant dans le path spécifié dans la CLI
- Création d'un zip, puis envoi à la plateforme ZetaPush
- Suivi de progression du déploiement dans la console

# Push en déployant seulement le code server avec un path spécifié
`zeta push --server-only /path/to/back`

- Déploiement du code back se trouvant dans le path spécifié dans la CLI
- Création d'un zip, puis envoi à la plateforme ZetaPush
- Suivi de progression du déploiement dans la console
- Les _custom cloud services_ déployés sont à présent accessible via l'autocompletion de l'IDE

**Comment by ghoullier** [comment]
La proposition actuelle sur les paramètres de la CLI ne permet pas de deployer plusieurs front et plusieurs back. Est ce qu'on se limite à un pour le moment?

**Comment by damienld22** [comment]
@ghoullier 

Pour l'instant je pense qu'il faut se limiter au déploiement d'un seul front et d'un seul back. 

Le fait de merger les 2 implique que dans le cas où nous voulons seulement forcer un path mais quand même publier le front et le back nous sommes obligé de faire : 

`zeta push --front ./static/front --back ./server`

Alors que ne pas merger les deux paramètres nous permet d'écrire : 

`zeta push --front ./static/front`

Je pense que chaque façon de faire a ses inconvénients, à voir ce qui est le plus courant

**Comment by damienld22** [comment]
zeta push

Déploie le code du développeur sur la plateforme zetapush
Fait un register si besoin

zeta push sans paramètre ET SANS fichier de conf déploiement les valeurs de convention

zeta push sans paramètre ET AVEC fichier de conf déploiement tout ce qui est configuré dans le fichier package.json/.zetarc

zeta push avec paramètre ne déploie que ce qui est indiqué via les paramètres
